name: Build fintegra-hello app
 
on: 
  push:
    branches:
      - master

jobs:
  compile:
    name: "Java ${{ matrix.java }} compile"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against java 8 and 11 ... because we can
        java: [11]
    steps:
    - uses: actions/checkout@master
    - name: "Setup java"
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: "Run Maven"
      run: mvn -B -f pom.xml clean compile
  build:
    name: "Build maven project"
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: "Set up JDK 11"
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: "Build and test project"
      run: mvn -B -f pom.xml clean verify
    - name: "Build Docker container"
      run: |
        mkdir buildroot
        mv target/*.jar docker-buildroot
        mv Dockerfile docker-buildroot
        docker build -t fintegra-hello:latest docker-buildroot
  pushGCR:
    name: "Pushing to GCR"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: "Pushing ..."
      uses: raccoondev/push-docker-gcr
      with:
        gcr_host: eu.gcr.io
        image_name: fintegra-hello
        image_tag: latest
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_GCR_SERVICE_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}